version: "3.8"

x-DATABASE_PASSWORD: &x-DATABASE_PASSWORD "45b6456b456b456b456b456b4561"
x-common-variables: &common-variables
  DATABASE_URL: "postgresql"
  DATABASE_PORT: 5432
  DATABASE_USER: "postgres"
  DATABASE_DATABASE: "serverprovisioning"

services:
  go-example:
    build: .
    restart: "no"
    environment:
      <<: *common-variables
      DATABASE_PASSWORD: *x-DATABASE_PASSWORD
    depends_on:
      - "postgresql"
    networks:
      my-network:

  postgresql:
    image: postgres:13-alpine
    restart: on-failure
    volumes:
      - type: volume
        source: postgresql
        target: /var/lib/postgresql/data
    shm_size: 128M
    stop_signal: SIGTERM
    environment:
      <<: *common-variables
      POSTGRES_PASSWORD: *x-DATABASE_PASSWORD
    networks:
      my-network:

volumes:
  postgresql:

networks:
  my-network: