version: "3.8"

x-DATABASE_PASSWORD: &x-DATABASE_PASSWORD "45b6456b456b456b456b456b4561"
x-DATABASE_DATABASE: &x-DATABASE_DATABASE "gorm-example"
x-common-variables: &common-variables
  DATABASE_URL: "postgresql"
  DATABASE_PORT: 5432
  DATABASE_USER: "postgres"
  DATABASE_DATABASE: *x-DATABASE_DATABASE

services:
  go-example:
    build: .
    restart: "no"
    environment:
      <<: *common-variables
      DATABASE_PASSWORD: *x-DATABASE_PASSWORD
    depends_on:
      - "postgresql"
    networks:
      my-network:

  postgresql:
    image: postgres:13-alpine
    restart: on-failure
    # to see all requests from server side https://stackoverflow.com/questions/57015003/log-all-queries-in-the-official-postgres-docker-image
    #command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - type: volume
        source: postgresql
        target: /var/lib/postgresql/data
    shm_size: 128M
    stop_signal: SIGTERM
    environment:
      <<: *common-variables
      POSTGRES_PASSWORD: *x-DATABASE_PASSWORD
      POSTGRES_DB: *x-DATABASE_DATABASE
    networks:
      my-network:

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: info@example.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'True'
#      <<: *common-variables
#      POSTGRES_PASSWORD: *x-DATABASE_PASSWORD
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    networks:
#      ts-provisioning-net:
#    restart: unless-stopped

volumes:
  postgresql:

networks:
  my-network: